// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessage.proto

package com.randioo.tiger_server.protocol;

public final class ClientMessage {
  private ClientMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class CSMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use CSMessage.newBuilder() to construct.
    private CSMessage() {
      initFields();
    }
    private CSMessage(boolean noInit) {}
    
    private static final CSMessage defaultInstance;
    public static CSMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public CSMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.tiger_server.protocol.ClientMessage.internal_static_com_randioo_tiger_server_protocol_CSMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.tiger_server.protocol.ClientMessage.internal_static_com_randioo_tiger_server_protocol_CSMessage_fieldAccessorTable;
    }
    
    // optional .com.randioo.tiger_server.protocol.LoginCheckAccountRequest LoginCheckAccountRequest = 1;
    public static final int LOGINCHECKACCOUNTREQUEST_FIELD_NUMBER = 1;
    private boolean hasLoginCheckAccountRequest;
    private com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest loginCheckAccountRequest_;
    public boolean hasLoginCheckAccountRequest() { return hasLoginCheckAccountRequest; }
    public com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest getLoginCheckAccountRequest() { return loginCheckAccountRequest_; }
    
    // optional .com.randioo.tiger_server.protocol.LoginCreateRoleRequest LoginCreateRoleRequest = 2;
    public static final int LOGINCREATEROLEREQUEST_FIELD_NUMBER = 2;
    private boolean hasLoginCreateRoleRequest;
    private com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest loginCreateRoleRequest_;
    public boolean hasLoginCreateRoleRequest() { return hasLoginCreateRoleRequest; }
    public com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest getLoginCreateRoleRequest() { return loginCreateRoleRequest_; }
    
    // optional .com.randioo.tiger_server.protocol.LoginGetRoleDataRequest LoginGetRoleDataRequest = 3;
    public static final int LOGINGETROLEDATAREQUEST_FIELD_NUMBER = 3;
    private boolean hasLoginGetRoleDataRequest;
    private com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest loginGetRoleDataRequest_;
    public boolean hasLoginGetRoleDataRequest() { return hasLoginGetRoleDataRequest; }
    public com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest getLoginGetRoleDataRequest() { return loginGetRoleDataRequest_; }
    
    // optional .com.randioo.tiger_server.protocol.GmCmdRequest GmCmdRequest = 4;
    public static final int GMCMDREQUEST_FIELD_NUMBER = 4;
    private boolean hasGmCmdRequest;
    private com.randioo.tiger_server.protocol.Gm.GmCmdRequest gmCmdRequest_;
    public boolean hasGmCmdRequest() { return hasGmCmdRequest; }
    public com.randioo.tiger_server.protocol.Gm.GmCmdRequest getGmCmdRequest() { return gmCmdRequest_; }
    
    // optional .com.randioo.tiger_server.protocol.TigerRequest tigerRequest = 5;
    public static final int TIGERREQUEST_FIELD_NUMBER = 5;
    private boolean hasTigerRequest;
    private com.randioo.tiger_server.protocol.Tiger.TigerRequest tigerRequest_;
    public boolean hasTigerRequest() { return hasTigerRequest; }
    public com.randioo.tiger_server.protocol.Tiger.TigerRequest getTigerRequest() { return tigerRequest_; }
    
    private void initFields() {
      loginCheckAccountRequest_ = com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest.getDefaultInstance();
      loginCreateRoleRequest_ = com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest.getDefaultInstance();
      loginGetRoleDataRequest_ = com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest.getDefaultInstance();
      gmCmdRequest_ = com.randioo.tiger_server.protocol.Gm.GmCmdRequest.getDefaultInstance();
      tigerRequest_ = com.randioo.tiger_server.protocol.Tiger.TigerRequest.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasLoginCheckAccountRequest()) {
        output.writeMessage(1, getLoginCheckAccountRequest());
      }
      if (hasLoginCreateRoleRequest()) {
        output.writeMessage(2, getLoginCreateRoleRequest());
      }
      if (hasLoginGetRoleDataRequest()) {
        output.writeMessage(3, getLoginGetRoleDataRequest());
      }
      if (hasGmCmdRequest()) {
        output.writeMessage(4, getGmCmdRequest());
      }
      if (hasTigerRequest()) {
        output.writeMessage(5, getTigerRequest());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasLoginCheckAccountRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getLoginCheckAccountRequest());
      }
      if (hasLoginCreateRoleRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLoginCreateRoleRequest());
      }
      if (hasLoginGetRoleDataRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getLoginGetRoleDataRequest());
      }
      if (hasGmCmdRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getGmCmdRequest());
      }
      if (hasTigerRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getTigerRequest());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.tiger_server.protocol.ClientMessage.CSMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.ClientMessage.CSMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.ClientMessage.CSMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.ClientMessage.CSMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.ClientMessage.CSMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.ClientMessage.CSMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.ClientMessage.CSMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.ClientMessage.CSMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.ClientMessage.CSMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.ClientMessage.CSMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.tiger_server.protocol.ClientMessage.CSMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.tiger_server.protocol.ClientMessage.CSMessage result;
      
      // Construct using com.randioo.tiger_server.protocol.ClientMessage.CSMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.tiger_server.protocol.ClientMessage.CSMessage();
        return builder;
      }
      
      protected com.randioo.tiger_server.protocol.ClientMessage.CSMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.tiger_server.protocol.ClientMessage.CSMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.tiger_server.protocol.ClientMessage.CSMessage.getDescriptor();
      }
      
      public com.randioo.tiger_server.protocol.ClientMessage.CSMessage getDefaultInstanceForType() {
        return com.randioo.tiger_server.protocol.ClientMessage.CSMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.tiger_server.protocol.ClientMessage.CSMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.tiger_server.protocol.ClientMessage.CSMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.tiger_server.protocol.ClientMessage.CSMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.tiger_server.protocol.ClientMessage.CSMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.tiger_server.protocol.ClientMessage.CSMessage) {
          return mergeFrom((com.randioo.tiger_server.protocol.ClientMessage.CSMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.tiger_server.protocol.ClientMessage.CSMessage other) {
        if (other == com.randioo.tiger_server.protocol.ClientMessage.CSMessage.getDefaultInstance()) return this;
        if (other.hasLoginCheckAccountRequest()) {
          mergeLoginCheckAccountRequest(other.getLoginCheckAccountRequest());
        }
        if (other.hasLoginCreateRoleRequest()) {
          mergeLoginCreateRoleRequest(other.getLoginCreateRoleRequest());
        }
        if (other.hasLoginGetRoleDataRequest()) {
          mergeLoginGetRoleDataRequest(other.getLoginGetRoleDataRequest());
        }
        if (other.hasGmCmdRequest()) {
          mergeGmCmdRequest(other.getGmCmdRequest());
        }
        if (other.hasTigerRequest()) {
          mergeTigerRequest(other.getTigerRequest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest.Builder subBuilder = com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest.newBuilder();
              if (hasLoginCheckAccountRequest()) {
                subBuilder.mergeFrom(getLoginCheckAccountRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginCheckAccountRequest(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest.Builder subBuilder = com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest.newBuilder();
              if (hasLoginCreateRoleRequest()) {
                subBuilder.mergeFrom(getLoginCreateRoleRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginCreateRoleRequest(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest.Builder subBuilder = com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest.newBuilder();
              if (hasLoginGetRoleDataRequest()) {
                subBuilder.mergeFrom(getLoginGetRoleDataRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginGetRoleDataRequest(subBuilder.buildPartial());
              break;
            }
            case 34: {
              com.randioo.tiger_server.protocol.Gm.GmCmdRequest.Builder subBuilder = com.randioo.tiger_server.protocol.Gm.GmCmdRequest.newBuilder();
              if (hasGmCmdRequest()) {
                subBuilder.mergeFrom(getGmCmdRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGmCmdRequest(subBuilder.buildPartial());
              break;
            }
            case 42: {
              com.randioo.tiger_server.protocol.Tiger.TigerRequest.Builder subBuilder = com.randioo.tiger_server.protocol.Tiger.TigerRequest.newBuilder();
              if (hasTigerRequest()) {
                subBuilder.mergeFrom(getTigerRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setTigerRequest(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .com.randioo.tiger_server.protocol.LoginCheckAccountRequest LoginCheckAccountRequest = 1;
      public boolean hasLoginCheckAccountRequest() {
        return result.hasLoginCheckAccountRequest();
      }
      public com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest getLoginCheckAccountRequest() {
        return result.getLoginCheckAccountRequest();
      }
      public Builder setLoginCheckAccountRequest(com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginCheckAccountRequest = true;
        result.loginCheckAccountRequest_ = value;
        return this;
      }
      public Builder setLoginCheckAccountRequest(com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest.Builder builderForValue) {
        result.hasLoginCheckAccountRequest = true;
        result.loginCheckAccountRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginCheckAccountRequest(com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest value) {
        if (result.hasLoginCheckAccountRequest() &&
            result.loginCheckAccountRequest_ != com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest.getDefaultInstance()) {
          result.loginCheckAccountRequest_ =
            com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest.newBuilder(result.loginCheckAccountRequest_).mergeFrom(value).buildPartial();
        } else {
          result.loginCheckAccountRequest_ = value;
        }
        result.hasLoginCheckAccountRequest = true;
        return this;
      }
      public Builder clearLoginCheckAccountRequest() {
        result.hasLoginCheckAccountRequest = false;
        result.loginCheckAccountRequest_ = com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.tiger_server.protocol.LoginCreateRoleRequest LoginCreateRoleRequest = 2;
      public boolean hasLoginCreateRoleRequest() {
        return result.hasLoginCreateRoleRequest();
      }
      public com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest getLoginCreateRoleRequest() {
        return result.getLoginCreateRoleRequest();
      }
      public Builder setLoginCreateRoleRequest(com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginCreateRoleRequest = true;
        result.loginCreateRoleRequest_ = value;
        return this;
      }
      public Builder setLoginCreateRoleRequest(com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest.Builder builderForValue) {
        result.hasLoginCreateRoleRequest = true;
        result.loginCreateRoleRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginCreateRoleRequest(com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest value) {
        if (result.hasLoginCreateRoleRequest() &&
            result.loginCreateRoleRequest_ != com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest.getDefaultInstance()) {
          result.loginCreateRoleRequest_ =
            com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest.newBuilder(result.loginCreateRoleRequest_).mergeFrom(value).buildPartial();
        } else {
          result.loginCreateRoleRequest_ = value;
        }
        result.hasLoginCreateRoleRequest = true;
        return this;
      }
      public Builder clearLoginCreateRoleRequest() {
        result.hasLoginCreateRoleRequest = false;
        result.loginCreateRoleRequest_ = com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.tiger_server.protocol.LoginGetRoleDataRequest LoginGetRoleDataRequest = 3;
      public boolean hasLoginGetRoleDataRequest() {
        return result.hasLoginGetRoleDataRequest();
      }
      public com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest getLoginGetRoleDataRequest() {
        return result.getLoginGetRoleDataRequest();
      }
      public Builder setLoginGetRoleDataRequest(com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginGetRoleDataRequest = true;
        result.loginGetRoleDataRequest_ = value;
        return this;
      }
      public Builder setLoginGetRoleDataRequest(com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest.Builder builderForValue) {
        result.hasLoginGetRoleDataRequest = true;
        result.loginGetRoleDataRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginGetRoleDataRequest(com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest value) {
        if (result.hasLoginGetRoleDataRequest() &&
            result.loginGetRoleDataRequest_ != com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest.getDefaultInstance()) {
          result.loginGetRoleDataRequest_ =
            com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest.newBuilder(result.loginGetRoleDataRequest_).mergeFrom(value).buildPartial();
        } else {
          result.loginGetRoleDataRequest_ = value;
        }
        result.hasLoginGetRoleDataRequest = true;
        return this;
      }
      public Builder clearLoginGetRoleDataRequest() {
        result.hasLoginGetRoleDataRequest = false;
        result.loginGetRoleDataRequest_ = com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.tiger_server.protocol.GmCmdRequest GmCmdRequest = 4;
      public boolean hasGmCmdRequest() {
        return result.hasGmCmdRequest();
      }
      public com.randioo.tiger_server.protocol.Gm.GmCmdRequest getGmCmdRequest() {
        return result.getGmCmdRequest();
      }
      public Builder setGmCmdRequest(com.randioo.tiger_server.protocol.Gm.GmCmdRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGmCmdRequest = true;
        result.gmCmdRequest_ = value;
        return this;
      }
      public Builder setGmCmdRequest(com.randioo.tiger_server.protocol.Gm.GmCmdRequest.Builder builderForValue) {
        result.hasGmCmdRequest = true;
        result.gmCmdRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeGmCmdRequest(com.randioo.tiger_server.protocol.Gm.GmCmdRequest value) {
        if (result.hasGmCmdRequest() &&
            result.gmCmdRequest_ != com.randioo.tiger_server.protocol.Gm.GmCmdRequest.getDefaultInstance()) {
          result.gmCmdRequest_ =
            com.randioo.tiger_server.protocol.Gm.GmCmdRequest.newBuilder(result.gmCmdRequest_).mergeFrom(value).buildPartial();
        } else {
          result.gmCmdRequest_ = value;
        }
        result.hasGmCmdRequest = true;
        return this;
      }
      public Builder clearGmCmdRequest() {
        result.hasGmCmdRequest = false;
        result.gmCmdRequest_ = com.randioo.tiger_server.protocol.Gm.GmCmdRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.tiger_server.protocol.TigerRequest tigerRequest = 5;
      public boolean hasTigerRequest() {
        return result.hasTigerRequest();
      }
      public com.randioo.tiger_server.protocol.Tiger.TigerRequest getTigerRequest() {
        return result.getTigerRequest();
      }
      public Builder setTigerRequest(com.randioo.tiger_server.protocol.Tiger.TigerRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasTigerRequest = true;
        result.tigerRequest_ = value;
        return this;
      }
      public Builder setTigerRequest(com.randioo.tiger_server.protocol.Tiger.TigerRequest.Builder builderForValue) {
        result.hasTigerRequest = true;
        result.tigerRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeTigerRequest(com.randioo.tiger_server.protocol.Tiger.TigerRequest value) {
        if (result.hasTigerRequest() &&
            result.tigerRequest_ != com.randioo.tiger_server.protocol.Tiger.TigerRequest.getDefaultInstance()) {
          result.tigerRequest_ =
            com.randioo.tiger_server.protocol.Tiger.TigerRequest.newBuilder(result.tigerRequest_).mergeFrom(value).buildPartial();
        } else {
          result.tigerRequest_ = value;
        }
        result.hasTigerRequest = true;
        return this;
      }
      public Builder clearTigerRequest() {
        result.hasTigerRequest = false;
        result.tigerRequest_ = com.randioo.tiger_server.protocol.Tiger.TigerRequest.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.tiger_server.protocol.CSMessage)
    }
    
    static {
      defaultInstance = new CSMessage(true);
      com.randioo.tiger_server.protocol.ClientMessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.tiger_server.protocol.CSMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_tiger_server_protocol_CSMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_tiger_server_protocol_CSMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ClientMessage.proto\022!com.randioo.tiger" +
      "_server.protocol\032\013Login.proto\032\010Gm.proto\032" +
      "\013Tiger.proto\"\260\003\n\tCSMessage\022]\n\030LoginCheck" +
      "AccountRequest\030\001 \001(\0132;.com.randioo.tiger" +
      "_server.protocol.LoginCheckAccountReques" +
      "t\022Y\n\026LoginCreateRoleRequest\030\002 \001(\01329.com." +
      "randioo.tiger_server.protocol.LoginCreat" +
      "eRoleRequest\022[\n\027LoginGetRoleDataRequest\030" +
      "\003 \001(\0132:.com.randioo.tiger_server.protoco" +
      "l.LoginGetRoleDataRequest\022E\n\014GmCmdReques",
      "t\030\004 \001(\0132/.com.randioo.tiger_server.proto" +
      "col.GmCmdRequest\022E\n\014tigerRequest\030\005 \001(\0132/" +
      ".com.randioo.tiger_server.protocol.Tiger" +
      "Request"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_tiger_server_protocol_CSMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_tiger_server_protocol_CSMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_tiger_server_protocol_CSMessage_descriptor,
              new java.lang.String[] { "LoginCheckAccountRequest", "LoginCreateRoleRequest", "LoginGetRoleDataRequest", "GmCmdRequest", "TigerRequest", },
              com.randioo.tiger_server.protocol.ClientMessage.CSMessage.class,
              com.randioo.tiger_server.protocol.ClientMessage.CSMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.tiger_server.protocol.Login.getDescriptor(),
          com.randioo.tiger_server.protocol.Gm.getDescriptor(),
          com.randioo.tiger_server.protocol.Tiger.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
