// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Entity.proto

package com.randioo.tiger_server.protocol;

public final class Entity {
  private Entity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class RoleData extends
      com.google.protobuf.GeneratedMessage {
    // Use RoleData.newBuilder() to construct.
    private RoleData() {
      initFields();
    }
    private RoleData(boolean noInit) {}
    
    private static final RoleData defaultInstance;
    public static RoleData getDefaultInstance() {
      return defaultInstance;
    }
    
    public RoleData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.tiger_server.protocol.Entity.internal_static_com_randioo_tiger_server_protocol_RoleData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.tiger_server.protocol.Entity.internal_static_com_randioo_tiger_server_protocol_RoleData_fieldAccessorTable;
    }
    
    // optional int32 roleId = 1;
    public static final int ROLEID_FIELD_NUMBER = 1;
    private boolean hasRoleId;
    private int roleId_ = 0;
    public boolean hasRoleId() { return hasRoleId; }
    public int getRoleId() { return roleId_; }
    
    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasRoleId()) {
        output.writeInt32(1, getRoleId());
      }
      if (hasName()) {
        output.writeString(2, getName());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasRoleId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getRoleId());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.tiger_server.protocol.Entity.RoleData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.RoleData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.RoleData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.RoleData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.RoleData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.RoleData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.RoleData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Entity.RoleData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Entity.RoleData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.RoleData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.tiger_server.protocol.Entity.RoleData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.tiger_server.protocol.Entity.RoleData result;
      
      // Construct using com.randioo.tiger_server.protocol.Entity.RoleData.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.tiger_server.protocol.Entity.RoleData();
        return builder;
      }
      
      protected com.randioo.tiger_server.protocol.Entity.RoleData internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.tiger_server.protocol.Entity.RoleData();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.tiger_server.protocol.Entity.RoleData.getDescriptor();
      }
      
      public com.randioo.tiger_server.protocol.Entity.RoleData getDefaultInstanceForType() {
        return com.randioo.tiger_server.protocol.Entity.RoleData.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.tiger_server.protocol.Entity.RoleData build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.tiger_server.protocol.Entity.RoleData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.tiger_server.protocol.Entity.RoleData buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.tiger_server.protocol.Entity.RoleData returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.tiger_server.protocol.Entity.RoleData) {
          return mergeFrom((com.randioo.tiger_server.protocol.Entity.RoleData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.tiger_server.protocol.Entity.RoleData other) {
        if (other == com.randioo.tiger_server.protocol.Entity.RoleData.getDefaultInstance()) return this;
        if (other.hasRoleId()) {
          setRoleId(other.getRoleId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setRoleId(input.readInt32());
              break;
            }
            case 18: {
              setName(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional int32 roleId = 1;
      public boolean hasRoleId() {
        return result.hasRoleId();
      }
      public int getRoleId() {
        return result.getRoleId();
      }
      public Builder setRoleId(int value) {
        result.hasRoleId = true;
        result.roleId_ = value;
        return this;
      }
      public Builder clearRoleId() {
        result.hasRoleId = false;
        result.roleId_ = 0;
        return this;
      }
      
      // optional string name = 2;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.tiger_server.protocol.RoleData)
    }
    
    static {
      defaultInstance = new RoleData(true);
      com.randioo.tiger_server.protocol.Entity.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.tiger_server.protocol.RoleData)
  }
  
  public static final class TigerData extends
      com.google.protobuf.GeneratedMessage {
    // Use TigerData.newBuilder() to construct.
    private TigerData() {
      initFields();
    }
    private TigerData(boolean noInit) {}
    
    private static final TigerData defaultInstance;
    public static TigerData getDefaultInstance() {
      return defaultInstance;
    }
    
    public TigerData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.tiger_server.protocol.Entity.internal_static_com_randioo_tiger_server_protocol_TigerData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.tiger_server.protocol.Entity.internal_static_com_randioo_tiger_server_protocol_TigerData_fieldAccessorTable;
    }
    
    // optional int32 reward = 1;
    public static final int REWARD_FIELD_NUMBER = 1;
    private boolean hasReward;
    private int reward_ = 0;
    public boolean hasReward() { return hasReward; }
    public int getReward() { return reward_; }
    
    // optional int32 fail = 2;
    public static final int FAIL_FIELD_NUMBER = 2;
    private boolean hasFail;
    private int fail_ = 0;
    public boolean hasFail() { return hasFail; }
    public int getFail() { return fail_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasReward()) {
        output.writeInt32(1, getReward());
      }
      if (hasFail()) {
        output.writeInt32(2, getFail());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasReward()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getReward());
      }
      if (hasFail()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getFail());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.tiger_server.protocol.Entity.TigerData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.TigerData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.TigerData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.TigerData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.TigerData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.TigerData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.TigerData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Entity.TigerData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Entity.TigerData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.TigerData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.tiger_server.protocol.Entity.TigerData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.tiger_server.protocol.Entity.TigerData result;
      
      // Construct using com.randioo.tiger_server.protocol.Entity.TigerData.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.tiger_server.protocol.Entity.TigerData();
        return builder;
      }
      
      protected com.randioo.tiger_server.protocol.Entity.TigerData internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.tiger_server.protocol.Entity.TigerData();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.tiger_server.protocol.Entity.TigerData.getDescriptor();
      }
      
      public com.randioo.tiger_server.protocol.Entity.TigerData getDefaultInstanceForType() {
        return com.randioo.tiger_server.protocol.Entity.TigerData.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.tiger_server.protocol.Entity.TigerData build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.tiger_server.protocol.Entity.TigerData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.tiger_server.protocol.Entity.TigerData buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.tiger_server.protocol.Entity.TigerData returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.tiger_server.protocol.Entity.TigerData) {
          return mergeFrom((com.randioo.tiger_server.protocol.Entity.TigerData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.tiger_server.protocol.Entity.TigerData other) {
        if (other == com.randioo.tiger_server.protocol.Entity.TigerData.getDefaultInstance()) return this;
        if (other.hasReward()) {
          setReward(other.getReward());
        }
        if (other.hasFail()) {
          setFail(other.getFail());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setReward(input.readInt32());
              break;
            }
            case 16: {
              setFail(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 reward = 1;
      public boolean hasReward() {
        return result.hasReward();
      }
      public int getReward() {
        return result.getReward();
      }
      public Builder setReward(int value) {
        result.hasReward = true;
        result.reward_ = value;
        return this;
      }
      public Builder clearReward() {
        result.hasReward = false;
        result.reward_ = 0;
        return this;
      }
      
      // optional int32 fail = 2;
      public boolean hasFail() {
        return result.hasFail();
      }
      public int getFail() {
        return result.getFail();
      }
      public Builder setFail(int value) {
        result.hasFail = true;
        result.fail_ = value;
        return this;
      }
      public Builder clearFail() {
        result.hasFail = false;
        result.fail_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.tiger_server.protocol.TigerData)
    }
    
    static {
      defaultInstance = new TigerData(true);
      com.randioo.tiger_server.protocol.Entity.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.tiger_server.protocol.TigerData)
  }
  
  public static final class RowData extends
      com.google.protobuf.GeneratedMessage {
    // Use RowData.newBuilder() to construct.
    private RowData() {
      initFields();
    }
    private RowData(boolean noInit) {}
    
    private static final RowData defaultInstance;
    public static RowData getDefaultInstance() {
      return defaultInstance;
    }
    
    public RowData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.tiger_server.protocol.Entity.internal_static_com_randioo_tiger_server_protocol_RowData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.tiger_server.protocol.Entity.internal_static_com_randioo_tiger_server_protocol_RowData_fieldAccessorTable;
    }
    
    // repeated int32 value = 1;
    public static final int VALUE_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> value_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.Integer> getValueList() {
      return value_;
    }
    public int getValueCount() { return value_.size(); }
    public int getValue(int index) {
      return value_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int element : getValueList()) {
        output.writeInt32(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int element : getValueList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getValueList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.tiger_server.protocol.Entity.RowData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.RowData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.RowData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.RowData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.RowData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.RowData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.RowData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Entity.RowData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Entity.RowData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.RowData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.tiger_server.protocol.Entity.RowData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.tiger_server.protocol.Entity.RowData result;
      
      // Construct using com.randioo.tiger_server.protocol.Entity.RowData.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.tiger_server.protocol.Entity.RowData();
        return builder;
      }
      
      protected com.randioo.tiger_server.protocol.Entity.RowData internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.tiger_server.protocol.Entity.RowData();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.tiger_server.protocol.Entity.RowData.getDescriptor();
      }
      
      public com.randioo.tiger_server.protocol.Entity.RowData getDefaultInstanceForType() {
        return com.randioo.tiger_server.protocol.Entity.RowData.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.tiger_server.protocol.Entity.RowData build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.tiger_server.protocol.Entity.RowData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.tiger_server.protocol.Entity.RowData buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.value_ != java.util.Collections.EMPTY_LIST) {
          result.value_ =
            java.util.Collections.unmodifiableList(result.value_);
        }
        com.randioo.tiger_server.protocol.Entity.RowData returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.tiger_server.protocol.Entity.RowData) {
          return mergeFrom((com.randioo.tiger_server.protocol.Entity.RowData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.tiger_server.protocol.Entity.RowData other) {
        if (other == com.randioo.tiger_server.protocol.Entity.RowData.getDefaultInstance()) return this;
        if (!other.value_.isEmpty()) {
          if (result.value_.isEmpty()) {
            result.value_ = new java.util.ArrayList<java.lang.Integer>();
          }
          result.value_.addAll(other.value_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              addValue(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addValue(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      
      // repeated int32 value = 1;
      public java.util.List<java.lang.Integer> getValueList() {
        return java.util.Collections.unmodifiableList(result.value_);
      }
      public int getValueCount() {
        return result.getValueCount();
      }
      public int getValue(int index) {
        return result.getValue(index);
      }
      public Builder setValue(int index, int value) {
        result.value_.set(index, value);
        return this;
      }
      public Builder addValue(int value) {
        if (result.value_.isEmpty()) {
          result.value_ = new java.util.ArrayList<java.lang.Integer>();
        }
        result.value_.add(value);
        return this;
      }
      public Builder addAllValue(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        if (result.value_.isEmpty()) {
          result.value_ = new java.util.ArrayList<java.lang.Integer>();
        }
        super.addAll(values, result.value_);
        return this;
      }
      public Builder clearValue() {
        result.value_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.tiger_server.protocol.RowData)
    }
    
    static {
      defaultInstance = new RowData(true);
      com.randioo.tiger_server.protocol.Entity.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.tiger_server.protocol.RowData)
  }
  
  public static final class RandomData extends
      com.google.protobuf.GeneratedMessage {
    // Use RandomData.newBuilder() to construct.
    private RandomData() {
      initFields();
    }
    private RandomData(boolean noInit) {}
    
    private static final RandomData defaultInstance;
    public static RandomData getDefaultInstance() {
      return defaultInstance;
    }
    
    public RandomData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.tiger_server.protocol.Entity.internal_static_com_randioo_tiger_server_protocol_RandomData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.tiger_server.protocol.Entity.internal_static_com_randioo_tiger_server_protocol_RandomData_fieldAccessorTable;
    }
    
    // repeated .com.randioo.tiger_server.protocol.RowData rowData = 1;
    public static final int ROWDATA_FIELD_NUMBER = 1;
    private java.util.List<com.randioo.tiger_server.protocol.Entity.RowData> rowData_ =
      java.util.Collections.emptyList();
    public java.util.List<com.randioo.tiger_server.protocol.Entity.RowData> getRowDataList() {
      return rowData_;
    }
    public int getRowDataCount() { return rowData_.size(); }
    public com.randioo.tiger_server.protocol.Entity.RowData getRowData(int index) {
      return rowData_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (com.randioo.tiger_server.protocol.Entity.RowData element : getRowDataList()) {
        output.writeMessage(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (com.randioo.tiger_server.protocol.Entity.RowData element : getRowDataList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.tiger_server.protocol.Entity.RandomData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.RandomData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.RandomData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.RandomData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.RandomData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.RandomData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.RandomData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Entity.RandomData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Entity.RandomData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Entity.RandomData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.tiger_server.protocol.Entity.RandomData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.tiger_server.protocol.Entity.RandomData result;
      
      // Construct using com.randioo.tiger_server.protocol.Entity.RandomData.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.tiger_server.protocol.Entity.RandomData();
        return builder;
      }
      
      protected com.randioo.tiger_server.protocol.Entity.RandomData internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.tiger_server.protocol.Entity.RandomData();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.tiger_server.protocol.Entity.RandomData.getDescriptor();
      }
      
      public com.randioo.tiger_server.protocol.Entity.RandomData getDefaultInstanceForType() {
        return com.randioo.tiger_server.protocol.Entity.RandomData.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.tiger_server.protocol.Entity.RandomData build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.tiger_server.protocol.Entity.RandomData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.tiger_server.protocol.Entity.RandomData buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.rowData_ != java.util.Collections.EMPTY_LIST) {
          result.rowData_ =
            java.util.Collections.unmodifiableList(result.rowData_);
        }
        com.randioo.tiger_server.protocol.Entity.RandomData returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.tiger_server.protocol.Entity.RandomData) {
          return mergeFrom((com.randioo.tiger_server.protocol.Entity.RandomData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.tiger_server.protocol.Entity.RandomData other) {
        if (other == com.randioo.tiger_server.protocol.Entity.RandomData.getDefaultInstance()) return this;
        if (!other.rowData_.isEmpty()) {
          if (result.rowData_.isEmpty()) {
            result.rowData_ = new java.util.ArrayList<com.randioo.tiger_server.protocol.Entity.RowData>();
          }
          result.rowData_.addAll(other.rowData_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.randioo.tiger_server.protocol.Entity.RowData.Builder subBuilder = com.randioo.tiger_server.protocol.Entity.RowData.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addRowData(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .com.randioo.tiger_server.protocol.RowData rowData = 1;
      public java.util.List<com.randioo.tiger_server.protocol.Entity.RowData> getRowDataList() {
        return java.util.Collections.unmodifiableList(result.rowData_);
      }
      public int getRowDataCount() {
        return result.getRowDataCount();
      }
      public com.randioo.tiger_server.protocol.Entity.RowData getRowData(int index) {
        return result.getRowData(index);
      }
      public Builder setRowData(int index, com.randioo.tiger_server.protocol.Entity.RowData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.rowData_.set(index, value);
        return this;
      }
      public Builder setRowData(int index, com.randioo.tiger_server.protocol.Entity.RowData.Builder builderForValue) {
        result.rowData_.set(index, builderForValue.build());
        return this;
      }
      public Builder addRowData(com.randioo.tiger_server.protocol.Entity.RowData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.rowData_.isEmpty()) {
          result.rowData_ = new java.util.ArrayList<com.randioo.tiger_server.protocol.Entity.RowData>();
        }
        result.rowData_.add(value);
        return this;
      }
      public Builder addRowData(com.randioo.tiger_server.protocol.Entity.RowData.Builder builderForValue) {
        if (result.rowData_.isEmpty()) {
          result.rowData_ = new java.util.ArrayList<com.randioo.tiger_server.protocol.Entity.RowData>();
        }
        result.rowData_.add(builderForValue.build());
        return this;
      }
      public Builder addAllRowData(
          java.lang.Iterable<? extends com.randioo.tiger_server.protocol.Entity.RowData> values) {
        if (result.rowData_.isEmpty()) {
          result.rowData_ = new java.util.ArrayList<com.randioo.tiger_server.protocol.Entity.RowData>();
        }
        super.addAll(values, result.rowData_);
        return this;
      }
      public Builder clearRowData() {
        result.rowData_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.tiger_server.protocol.RandomData)
    }
    
    static {
      defaultInstance = new RandomData(true);
      com.randioo.tiger_server.protocol.Entity.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.tiger_server.protocol.RandomData)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_tiger_server_protocol_RoleData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_tiger_server_protocol_RoleData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_tiger_server_protocol_TigerData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_tiger_server_protocol_TigerData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_tiger_server_protocol_RowData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_tiger_server_protocol_RowData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_tiger_server_protocol_RandomData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_tiger_server_protocol_RandomData_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Entity.proto\022!com.randioo.tiger_server" +
      ".protocol\"(\n\010RoleData\022\016\n\006roleId\030\001 \001(\005\022\014\n" +
      "\004name\030\002 \001(\t\")\n\tTigerData\022\016\n\006reward\030\001 \001(\005" +
      "\022\014\n\004fail\030\002 \001(\005\"\030\n\007RowData\022\r\n\005value\030\001 \003(\005" +
      "\"I\n\nRandomData\022;\n\007rowData\030\001 \003(\0132*.com.ra" +
      "ndioo.tiger_server.protocol.RowData"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_tiger_server_protocol_RoleData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_tiger_server_protocol_RoleData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_tiger_server_protocol_RoleData_descriptor,
              new java.lang.String[] { "RoleId", "Name", },
              com.randioo.tiger_server.protocol.Entity.RoleData.class,
              com.randioo.tiger_server.protocol.Entity.RoleData.Builder.class);
          internal_static_com_randioo_tiger_server_protocol_TigerData_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_randioo_tiger_server_protocol_TigerData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_tiger_server_protocol_TigerData_descriptor,
              new java.lang.String[] { "Reward", "Fail", },
              com.randioo.tiger_server.protocol.Entity.TigerData.class,
              com.randioo.tiger_server.protocol.Entity.TigerData.Builder.class);
          internal_static_com_randioo_tiger_server_protocol_RowData_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_randioo_tiger_server_protocol_RowData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_tiger_server_protocol_RowData_descriptor,
              new java.lang.String[] { "Value", },
              com.randioo.tiger_server.protocol.Entity.RowData.class,
              com.randioo.tiger_server.protocol.Entity.RowData.Builder.class);
          internal_static_com_randioo_tiger_server_protocol_RandomData_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_randioo_tiger_server_protocol_RandomData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_tiger_server_protocol_RandomData_descriptor,
              new java.lang.String[] { "RowData", },
              com.randioo.tiger_server.protocol.Entity.RandomData.class,
              com.randioo.tiger_server.protocol.Entity.RandomData.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
