// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Gm.proto

package com.randioo.tiger_server.protocol;

public final class Gm {
  private Gm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class GmCmdRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use GmCmdRequest.newBuilder() to construct.
    private GmCmdRequest() {
      initFields();
    }
    private GmCmdRequest(boolean noInit) {}
    
    private static final GmCmdRequest defaultInstance;
    public static GmCmdRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public GmCmdRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.tiger_server.protocol.Gm.internal_static_com_randioo_tiger_server_protocol_GmCmdRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.tiger_server.protocol.Gm.internal_static_com_randioo_tiger_server_protocol_GmCmdRequest_fieldAccessorTable;
    }
    
    // optional string cmd = 1;
    public static final int CMD_FIELD_NUMBER = 1;
    private boolean hasCmd;
    private java.lang.String cmd_ = "";
    public boolean hasCmd() { return hasCmd; }
    public java.lang.String getCmd() { return cmd_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasCmd()) {
        output.writeString(1, getCmd());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasCmd()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getCmd());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.tiger_server.protocol.Gm.GmCmdRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Gm.GmCmdRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Gm.GmCmdRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Gm.GmCmdRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Gm.GmCmdRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Gm.GmCmdRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Gm.GmCmdRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Gm.GmCmdRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Gm.GmCmdRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Gm.GmCmdRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.tiger_server.protocol.Gm.GmCmdRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.tiger_server.protocol.Gm.GmCmdRequest result;
      
      // Construct using com.randioo.tiger_server.protocol.Gm.GmCmdRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.tiger_server.protocol.Gm.GmCmdRequest();
        return builder;
      }
      
      protected com.randioo.tiger_server.protocol.Gm.GmCmdRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.tiger_server.protocol.Gm.GmCmdRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.tiger_server.protocol.Gm.GmCmdRequest.getDescriptor();
      }
      
      public com.randioo.tiger_server.protocol.Gm.GmCmdRequest getDefaultInstanceForType() {
        return com.randioo.tiger_server.protocol.Gm.GmCmdRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.tiger_server.protocol.Gm.GmCmdRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.tiger_server.protocol.Gm.GmCmdRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.tiger_server.protocol.Gm.GmCmdRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.tiger_server.protocol.Gm.GmCmdRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.tiger_server.protocol.Gm.GmCmdRequest) {
          return mergeFrom((com.randioo.tiger_server.protocol.Gm.GmCmdRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.tiger_server.protocol.Gm.GmCmdRequest other) {
        if (other == com.randioo.tiger_server.protocol.Gm.GmCmdRequest.getDefaultInstance()) return this;
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setCmd(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string cmd = 1;
      public boolean hasCmd() {
        return result.hasCmd();
      }
      public java.lang.String getCmd() {
        return result.getCmd();
      }
      public Builder setCmd(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasCmd = true;
        result.cmd_ = value;
        return this;
      }
      public Builder clearCmd() {
        result.hasCmd = false;
        result.cmd_ = getDefaultInstance().getCmd();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.tiger_server.protocol.GmCmdRequest)
    }
    
    static {
      defaultInstance = new GmCmdRequest(true);
      com.randioo.tiger_server.protocol.Gm.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.tiger_server.protocol.GmCmdRequest)
  }
  
  public static final class GmCmdResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use GmCmdResponse.newBuilder() to construct.
    private GmCmdResponse() {
      initFields();
    }
    private GmCmdResponse(boolean noInit) {}
    
    private static final GmCmdResponse defaultInstance;
    public static GmCmdResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public GmCmdResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.tiger_server.protocol.Gm.internal_static_com_randioo_tiger_server_protocol_GmCmdResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.tiger_server.protocol.Gm.internal_static_com_randioo_tiger_server_protocol_GmCmdResponse_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.tiger_server.protocol.Gm.GmCmdResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Gm.GmCmdResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Gm.GmCmdResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Gm.GmCmdResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Gm.GmCmdResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Gm.GmCmdResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Gm.GmCmdResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Gm.GmCmdResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Gm.GmCmdResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Gm.GmCmdResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.tiger_server.protocol.Gm.GmCmdResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.tiger_server.protocol.Gm.GmCmdResponse result;
      
      // Construct using com.randioo.tiger_server.protocol.Gm.GmCmdResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.tiger_server.protocol.Gm.GmCmdResponse();
        return builder;
      }
      
      protected com.randioo.tiger_server.protocol.Gm.GmCmdResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.tiger_server.protocol.Gm.GmCmdResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.tiger_server.protocol.Gm.GmCmdResponse.getDescriptor();
      }
      
      public com.randioo.tiger_server.protocol.Gm.GmCmdResponse getDefaultInstanceForType() {
        return com.randioo.tiger_server.protocol.Gm.GmCmdResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.tiger_server.protocol.Gm.GmCmdResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.tiger_server.protocol.Gm.GmCmdResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.tiger_server.protocol.Gm.GmCmdResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.tiger_server.protocol.Gm.GmCmdResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.tiger_server.protocol.Gm.GmCmdResponse) {
          return mergeFrom((com.randioo.tiger_server.protocol.Gm.GmCmdResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.tiger_server.protocol.Gm.GmCmdResponse other) {
        if (other == com.randioo.tiger_server.protocol.Gm.GmCmdResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.randioo.tiger_server.protocol.GmCmdResponse)
    }
    
    static {
      defaultInstance = new GmCmdResponse(true);
      com.randioo.tiger_server.protocol.Gm.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.tiger_server.protocol.GmCmdResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_tiger_server_protocol_GmCmdRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_tiger_server_protocol_GmCmdRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_tiger_server_protocol_GmCmdResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_tiger_server_protocol_GmCmdResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010Gm.proto\022!com.randioo.tiger_server.pro" +
      "tocol\"\033\n\014GmCmdRequest\022\013\n\003cmd\030\001 \001(\t\"\017\n\rGm" +
      "CmdResponse"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_tiger_server_protocol_GmCmdRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_tiger_server_protocol_GmCmdRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_tiger_server_protocol_GmCmdRequest_descriptor,
              new java.lang.String[] { "Cmd", },
              com.randioo.tiger_server.protocol.Gm.GmCmdRequest.class,
              com.randioo.tiger_server.protocol.Gm.GmCmdRequest.Builder.class);
          internal_static_com_randioo_tiger_server_protocol_GmCmdResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_randioo_tiger_server_protocol_GmCmdResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_tiger_server_protocol_GmCmdResponse_descriptor,
              new java.lang.String[] { },
              com.randioo.tiger_server.protocol.Gm.GmCmdResponse.class,
              com.randioo.tiger_server.protocol.Gm.GmCmdResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
