// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Login.proto

package com.randioo.tiger_server.protocol;

public final class Login {
  private Login() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class LoginCheckAccountRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use LoginCheckAccountRequest.newBuilder() to construct.
    private LoginCheckAccountRequest() {
      initFields();
    }
    private LoginCheckAccountRequest(boolean noInit) {}
    
    private static final LoginCheckAccountRequest defaultInstance;
    public static LoginCheckAccountRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public LoginCheckAccountRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.tiger_server.protocol.Login.internal_static_com_randioo_tiger_server_protocol_LoginCheckAccountRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.tiger_server.protocol.Login.internal_static_com_randioo_tiger_server_protocol_LoginCheckAccountRequest_fieldAccessorTable;
    }
    
    // optional string account = 1;
    public static final int ACCOUNT_FIELD_NUMBER = 1;
    private boolean hasAccount;
    private java.lang.String account_ = "";
    public boolean hasAccount() { return hasAccount; }
    public java.lang.String getAccount() { return account_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasAccount()) {
        output.writeString(1, getAccount());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasAccount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getAccount());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest result;
      
      // Construct using com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest();
        return builder;
      }
      
      protected com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest.getDescriptor();
      }
      
      public com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest getDefaultInstanceForType() {
        return com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest) {
          return mergeFrom((com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest other) {
        if (other == com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest.getDefaultInstance()) return this;
        if (other.hasAccount()) {
          setAccount(other.getAccount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setAccount(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string account = 1;
      public boolean hasAccount() {
        return result.hasAccount();
      }
      public java.lang.String getAccount() {
        return result.getAccount();
      }
      public Builder setAccount(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAccount = true;
        result.account_ = value;
        return this;
      }
      public Builder clearAccount() {
        result.hasAccount = false;
        result.account_ = getDefaultInstance().getAccount();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.tiger_server.protocol.LoginCheckAccountRequest)
    }
    
    static {
      defaultInstance = new LoginCheckAccountRequest(true);
      com.randioo.tiger_server.protocol.Login.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.tiger_server.protocol.LoginCheckAccountRequest)
  }
  
  public static final class LoginCheckAccountResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use LoginCheckAccountResponse.newBuilder() to construct.
    private LoginCheckAccountResponse() {
      initFields();
    }
    private LoginCheckAccountResponse(boolean noInit) {}
    
    private static final LoginCheckAccountResponse defaultInstance;
    public static LoginCheckAccountResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public LoginCheckAccountResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.tiger_server.protocol.Login.internal_static_com_randioo_tiger_server_protocol_LoginCheckAccountResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.tiger_server.protocol.Login.internal_static_com_randioo_tiger_server_protocol_LoginCheckAccountResponse_fieldAccessorTable;
    }
    
    // optional int32 errorCode = 1 [default = 1];
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private boolean hasErrorCode;
    private int errorCode_ = 1;
    public boolean hasErrorCode() { return hasErrorCode; }
    public int getErrorCode() { return errorCode_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasErrorCode()) {
        output.writeInt32(1, getErrorCode());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasErrorCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getErrorCode());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse result;
      
      // Construct using com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse();
        return builder;
      }
      
      protected com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse.getDescriptor();
      }
      
      public com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse getDefaultInstanceForType() {
        return com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse) {
          return mergeFrom((com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse other) {
        if (other == com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setErrorCode(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 errorCode = 1 [default = 1];
      public boolean hasErrorCode() {
        return result.hasErrorCode();
      }
      public int getErrorCode() {
        return result.getErrorCode();
      }
      public Builder setErrorCode(int value) {
        result.hasErrorCode = true;
        result.errorCode_ = value;
        return this;
      }
      public Builder clearErrorCode() {
        result.hasErrorCode = false;
        result.errorCode_ = 1;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.tiger_server.protocol.LoginCheckAccountResponse)
    }
    
    static {
      defaultInstance = new LoginCheckAccountResponse(true);
      com.randioo.tiger_server.protocol.Login.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.tiger_server.protocol.LoginCheckAccountResponse)
  }
  
  public static final class LoginCreateRoleRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use LoginCreateRoleRequest.newBuilder() to construct.
    private LoginCreateRoleRequest() {
      initFields();
    }
    private LoginCreateRoleRequest(boolean noInit) {}
    
    private static final LoginCreateRoleRequest defaultInstance;
    public static LoginCreateRoleRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public LoginCreateRoleRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.tiger_server.protocol.Login.internal_static_com_randioo_tiger_server_protocol_LoginCreateRoleRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.tiger_server.protocol.Login.internal_static_com_randioo_tiger_server_protocol_LoginCreateRoleRequest_fieldAccessorTable;
    }
    
    // optional string account = 1;
    public static final int ACCOUNT_FIELD_NUMBER = 1;
    private boolean hasAccount;
    private java.lang.String account_ = "";
    public boolean hasAccount() { return hasAccount; }
    public java.lang.String getAccount() { return account_; }
    
    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasAccount()) {
        output.writeString(1, getAccount());
      }
      if (hasName()) {
        output.writeString(2, getName());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasAccount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getAccount());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest result;
      
      // Construct using com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest();
        return builder;
      }
      
      protected com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest.getDescriptor();
      }
      
      public com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest getDefaultInstanceForType() {
        return com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest) {
          return mergeFrom((com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest other) {
        if (other == com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest.getDefaultInstance()) return this;
        if (other.hasAccount()) {
          setAccount(other.getAccount());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setAccount(input.readString());
              break;
            }
            case 18: {
              setName(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string account = 1;
      public boolean hasAccount() {
        return result.hasAccount();
      }
      public java.lang.String getAccount() {
        return result.getAccount();
      }
      public Builder setAccount(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAccount = true;
        result.account_ = value;
        return this;
      }
      public Builder clearAccount() {
        result.hasAccount = false;
        result.account_ = getDefaultInstance().getAccount();
        return this;
      }
      
      // optional string name = 2;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.tiger_server.protocol.LoginCreateRoleRequest)
    }
    
    static {
      defaultInstance = new LoginCreateRoleRequest(true);
      com.randioo.tiger_server.protocol.Login.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.tiger_server.protocol.LoginCreateRoleRequest)
  }
  
  public static final class LoginCreateRoleResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use LoginCreateRoleResponse.newBuilder() to construct.
    private LoginCreateRoleResponse() {
      initFields();
    }
    private LoginCreateRoleResponse(boolean noInit) {}
    
    private static final LoginCreateRoleResponse defaultInstance;
    public static LoginCreateRoleResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public LoginCreateRoleResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.tiger_server.protocol.Login.internal_static_com_randioo_tiger_server_protocol_LoginCreateRoleResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.tiger_server.protocol.Login.internal_static_com_randioo_tiger_server_protocol_LoginCreateRoleResponse_fieldAccessorTable;
    }
    
    // optional int32 errorCode = 1 [default = 1];
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private boolean hasErrorCode;
    private int errorCode_ = 1;
    public boolean hasErrorCode() { return hasErrorCode; }
    public int getErrorCode() { return errorCode_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasErrorCode()) {
        output.writeInt32(1, getErrorCode());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasErrorCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getErrorCode());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse result;
      
      // Construct using com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse();
        return builder;
      }
      
      protected com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse.getDescriptor();
      }
      
      public com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse getDefaultInstanceForType() {
        return com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse) {
          return mergeFrom((com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse other) {
        if (other == com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setErrorCode(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 errorCode = 1 [default = 1];
      public boolean hasErrorCode() {
        return result.hasErrorCode();
      }
      public int getErrorCode() {
        return result.getErrorCode();
      }
      public Builder setErrorCode(int value) {
        result.hasErrorCode = true;
        result.errorCode_ = value;
        return this;
      }
      public Builder clearErrorCode() {
        result.hasErrorCode = false;
        result.errorCode_ = 1;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.tiger_server.protocol.LoginCreateRoleResponse)
    }
    
    static {
      defaultInstance = new LoginCreateRoleResponse(true);
      com.randioo.tiger_server.protocol.Login.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.tiger_server.protocol.LoginCreateRoleResponse)
  }
  
  public static final class LoginGetRoleDataRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use LoginGetRoleDataRequest.newBuilder() to construct.
    private LoginGetRoleDataRequest() {
      initFields();
    }
    private LoginGetRoleDataRequest(boolean noInit) {}
    
    private static final LoginGetRoleDataRequest defaultInstance;
    public static LoginGetRoleDataRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public LoginGetRoleDataRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.tiger_server.protocol.Login.internal_static_com_randioo_tiger_server_protocol_LoginGetRoleDataRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.tiger_server.protocol.Login.internal_static_com_randioo_tiger_server_protocol_LoginGetRoleDataRequest_fieldAccessorTable;
    }
    
    // optional string account = 1;
    public static final int ACCOUNT_FIELD_NUMBER = 1;
    private boolean hasAccount;
    private java.lang.String account_ = "";
    public boolean hasAccount() { return hasAccount; }
    public java.lang.String getAccount() { return account_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasAccount()) {
        output.writeString(1, getAccount());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasAccount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getAccount());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest result;
      
      // Construct using com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest();
        return builder;
      }
      
      protected com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest.getDescriptor();
      }
      
      public com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest getDefaultInstanceForType() {
        return com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest) {
          return mergeFrom((com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest other) {
        if (other == com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest.getDefaultInstance()) return this;
        if (other.hasAccount()) {
          setAccount(other.getAccount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setAccount(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string account = 1;
      public boolean hasAccount() {
        return result.hasAccount();
      }
      public java.lang.String getAccount() {
        return result.getAccount();
      }
      public Builder setAccount(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAccount = true;
        result.account_ = value;
        return this;
      }
      public Builder clearAccount() {
        result.hasAccount = false;
        result.account_ = getDefaultInstance().getAccount();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.tiger_server.protocol.LoginGetRoleDataRequest)
    }
    
    static {
      defaultInstance = new LoginGetRoleDataRequest(true);
      com.randioo.tiger_server.protocol.Login.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.tiger_server.protocol.LoginGetRoleDataRequest)
  }
  
  public static final class LoginGetRoleDataResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use LoginGetRoleDataResponse.newBuilder() to construct.
    private LoginGetRoleDataResponse() {
      initFields();
    }
    private LoginGetRoleDataResponse(boolean noInit) {}
    
    private static final LoginGetRoleDataResponse defaultInstance;
    public static LoginGetRoleDataResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public LoginGetRoleDataResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.tiger_server.protocol.Login.internal_static_com_randioo_tiger_server_protocol_LoginGetRoleDataResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.tiger_server.protocol.Login.internal_static_com_randioo_tiger_server_protocol_LoginGetRoleDataResponse_fieldAccessorTable;
    }
    
    // optional int32 errorCode = 1 [default = 1];
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private boolean hasErrorCode;
    private int errorCode_ = 1;
    public boolean hasErrorCode() { return hasErrorCode; }
    public int getErrorCode() { return errorCode_; }
    
    // optional int32 serverTime = 2;
    public static final int SERVERTIME_FIELD_NUMBER = 2;
    private boolean hasServerTime;
    private int serverTime_ = 0;
    public boolean hasServerTime() { return hasServerTime; }
    public int getServerTime() { return serverTime_; }
    
    // optional .com.randioo.tiger_server.protocol.RoleData roleData = 3;
    public static final int ROLEDATA_FIELD_NUMBER = 3;
    private boolean hasRoleData;
    private com.randioo.tiger_server.protocol.Entity.RoleData roleData_;
    public boolean hasRoleData() { return hasRoleData; }
    public com.randioo.tiger_server.protocol.Entity.RoleData getRoleData() { return roleData_; }
    
    private void initFields() {
      roleData_ = com.randioo.tiger_server.protocol.Entity.RoleData.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasErrorCode()) {
        output.writeInt32(1, getErrorCode());
      }
      if (hasServerTime()) {
        output.writeInt32(2, getServerTime());
      }
      if (hasRoleData()) {
        output.writeMessage(3, getRoleData());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasErrorCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getErrorCode());
      }
      if (hasServerTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getServerTime());
      }
      if (hasRoleData()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getRoleData());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse result;
      
      // Construct using com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse();
        return builder;
      }
      
      protected com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse.getDescriptor();
      }
      
      public com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse getDefaultInstanceForType() {
        return com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse) {
          return mergeFrom((com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse other) {
        if (other == com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasServerTime()) {
          setServerTime(other.getServerTime());
        }
        if (other.hasRoleData()) {
          mergeRoleData(other.getRoleData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setErrorCode(input.readInt32());
              break;
            }
            case 16: {
              setServerTime(input.readInt32());
              break;
            }
            case 26: {
              com.randioo.tiger_server.protocol.Entity.RoleData.Builder subBuilder = com.randioo.tiger_server.protocol.Entity.RoleData.newBuilder();
              if (hasRoleData()) {
                subBuilder.mergeFrom(getRoleData());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setRoleData(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional int32 errorCode = 1 [default = 1];
      public boolean hasErrorCode() {
        return result.hasErrorCode();
      }
      public int getErrorCode() {
        return result.getErrorCode();
      }
      public Builder setErrorCode(int value) {
        result.hasErrorCode = true;
        result.errorCode_ = value;
        return this;
      }
      public Builder clearErrorCode() {
        result.hasErrorCode = false;
        result.errorCode_ = 1;
        return this;
      }
      
      // optional int32 serverTime = 2;
      public boolean hasServerTime() {
        return result.hasServerTime();
      }
      public int getServerTime() {
        return result.getServerTime();
      }
      public Builder setServerTime(int value) {
        result.hasServerTime = true;
        result.serverTime_ = value;
        return this;
      }
      public Builder clearServerTime() {
        result.hasServerTime = false;
        result.serverTime_ = 0;
        return this;
      }
      
      // optional .com.randioo.tiger_server.protocol.RoleData roleData = 3;
      public boolean hasRoleData() {
        return result.hasRoleData();
      }
      public com.randioo.tiger_server.protocol.Entity.RoleData getRoleData() {
        return result.getRoleData();
      }
      public Builder setRoleData(com.randioo.tiger_server.protocol.Entity.RoleData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasRoleData = true;
        result.roleData_ = value;
        return this;
      }
      public Builder setRoleData(com.randioo.tiger_server.protocol.Entity.RoleData.Builder builderForValue) {
        result.hasRoleData = true;
        result.roleData_ = builderForValue.build();
        return this;
      }
      public Builder mergeRoleData(com.randioo.tiger_server.protocol.Entity.RoleData value) {
        if (result.hasRoleData() &&
            result.roleData_ != com.randioo.tiger_server.protocol.Entity.RoleData.getDefaultInstance()) {
          result.roleData_ =
            com.randioo.tiger_server.protocol.Entity.RoleData.newBuilder(result.roleData_).mergeFrom(value).buildPartial();
        } else {
          result.roleData_ = value;
        }
        result.hasRoleData = true;
        return this;
      }
      public Builder clearRoleData() {
        result.hasRoleData = false;
        result.roleData_ = com.randioo.tiger_server.protocol.Entity.RoleData.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.tiger_server.protocol.LoginGetRoleDataResponse)
    }
    
    static {
      defaultInstance = new LoginGetRoleDataResponse(true);
      com.randioo.tiger_server.protocol.Login.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.tiger_server.protocol.LoginGetRoleDataResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_tiger_server_protocol_LoginCheckAccountRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_tiger_server_protocol_LoginCheckAccountRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_tiger_server_protocol_LoginCheckAccountResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_tiger_server_protocol_LoginCheckAccountResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_tiger_server_protocol_LoginCreateRoleRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_tiger_server_protocol_LoginCreateRoleRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_tiger_server_protocol_LoginCreateRoleResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_tiger_server_protocol_LoginCreateRoleResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_tiger_server_protocol_LoginGetRoleDataRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_tiger_server_protocol_LoginGetRoleDataRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_tiger_server_protocol_LoginGetRoleDataResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_tiger_server_protocol_LoginGetRoleDataResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Login.proto\022!com.randioo.tiger_server." +
      "protocol\032\014Entity.proto\"+\n\030LoginCheckAcco" +
      "untRequest\022\017\n\007account\030\001 \001(\t\"1\n\031LoginChec" +
      "kAccountResponse\022\024\n\terrorCode\030\001 \001(\005:\0011\"7" +
      "\n\026LoginCreateRoleRequest\022\017\n\007account\030\001 \001(" +
      "\t\022\014\n\004name\030\002 \001(\t\"/\n\027LoginCreateRoleRespon" +
      "se\022\024\n\terrorCode\030\001 \001(\005:\0011\"*\n\027LoginGetRole" +
      "DataRequest\022\017\n\007account\030\001 \001(\t\"\203\001\n\030LoginGe" +
      "tRoleDataResponse\022\024\n\terrorCode\030\001 \001(\005:\0011\022" +
      "\022\n\nserverTime\030\002 \001(\005\022=\n\010roleData\030\003 \001(\0132+.",
      "com.randioo.tiger_server.protocol.RoleDa" +
      "ta"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_tiger_server_protocol_LoginCheckAccountRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_tiger_server_protocol_LoginCheckAccountRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_tiger_server_protocol_LoginCheckAccountRequest_descriptor,
              new java.lang.String[] { "Account", },
              com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest.class,
              com.randioo.tiger_server.protocol.Login.LoginCheckAccountRequest.Builder.class);
          internal_static_com_randioo_tiger_server_protocol_LoginCheckAccountResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_randioo_tiger_server_protocol_LoginCheckAccountResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_tiger_server_protocol_LoginCheckAccountResponse_descriptor,
              new java.lang.String[] { "ErrorCode", },
              com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse.class,
              com.randioo.tiger_server.protocol.Login.LoginCheckAccountResponse.Builder.class);
          internal_static_com_randioo_tiger_server_protocol_LoginCreateRoleRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_randioo_tiger_server_protocol_LoginCreateRoleRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_tiger_server_protocol_LoginCreateRoleRequest_descriptor,
              new java.lang.String[] { "Account", "Name", },
              com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest.class,
              com.randioo.tiger_server.protocol.Login.LoginCreateRoleRequest.Builder.class);
          internal_static_com_randioo_tiger_server_protocol_LoginCreateRoleResponse_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_randioo_tiger_server_protocol_LoginCreateRoleResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_tiger_server_protocol_LoginCreateRoleResponse_descriptor,
              new java.lang.String[] { "ErrorCode", },
              com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse.class,
              com.randioo.tiger_server.protocol.Login.LoginCreateRoleResponse.Builder.class);
          internal_static_com_randioo_tiger_server_protocol_LoginGetRoleDataRequest_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_com_randioo_tiger_server_protocol_LoginGetRoleDataRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_tiger_server_protocol_LoginGetRoleDataRequest_descriptor,
              new java.lang.String[] { "Account", },
              com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest.class,
              com.randioo.tiger_server.protocol.Login.LoginGetRoleDataRequest.Builder.class);
          internal_static_com_randioo_tiger_server_protocol_LoginGetRoleDataResponse_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_com_randioo_tiger_server_protocol_LoginGetRoleDataResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_tiger_server_protocol_LoginGetRoleDataResponse_descriptor,
              new java.lang.String[] { "ErrorCode", "ServerTime", "RoleData", },
              com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse.class,
              com.randioo.tiger_server.protocol.Login.LoginGetRoleDataResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.tiger_server.protocol.Entity.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
