// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Tiger.proto

package com.randioo.tiger_server.protocol;

public final class Tiger {
  private Tiger() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class TigerRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use TigerRequest.newBuilder() to construct.
    private TigerRequest() {
      initFields();
    }
    private TigerRequest(boolean noInit) {}
    
    private static final TigerRequest defaultInstance;
    public static TigerRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public TigerRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.tiger_server.protocol.Tiger.internal_static_com_randioo_tiger_server_protocol_TigerRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.tiger_server.protocol.Tiger.internal_static_com_randioo_tiger_server_protocol_TigerRequest_fieldAccessorTable;
    }
    
    // optional int32 ruleId = 1;
    public static final int RULEID_FIELD_NUMBER = 1;
    private boolean hasRuleId;
    private int ruleId_ = 0;
    public boolean hasRuleId() { return hasRuleId; }
    public int getRuleId() { return ruleId_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasRuleId()) {
        output.writeInt32(1, getRuleId());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasRuleId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getRuleId());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.tiger_server.protocol.Tiger.TigerRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Tiger.TigerRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Tiger.TigerRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Tiger.TigerRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Tiger.TigerRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Tiger.TigerRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Tiger.TigerRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Tiger.TigerRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Tiger.TigerRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Tiger.TigerRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.tiger_server.protocol.Tiger.TigerRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.tiger_server.protocol.Tiger.TigerRequest result;
      
      // Construct using com.randioo.tiger_server.protocol.Tiger.TigerRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.tiger_server.protocol.Tiger.TigerRequest();
        return builder;
      }
      
      protected com.randioo.tiger_server.protocol.Tiger.TigerRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.tiger_server.protocol.Tiger.TigerRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.tiger_server.protocol.Tiger.TigerRequest.getDescriptor();
      }
      
      public com.randioo.tiger_server.protocol.Tiger.TigerRequest getDefaultInstanceForType() {
        return com.randioo.tiger_server.protocol.Tiger.TigerRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.tiger_server.protocol.Tiger.TigerRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.tiger_server.protocol.Tiger.TigerRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.tiger_server.protocol.Tiger.TigerRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.tiger_server.protocol.Tiger.TigerRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.tiger_server.protocol.Tiger.TigerRequest) {
          return mergeFrom((com.randioo.tiger_server.protocol.Tiger.TigerRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.tiger_server.protocol.Tiger.TigerRequest other) {
        if (other == com.randioo.tiger_server.protocol.Tiger.TigerRequest.getDefaultInstance()) return this;
        if (other.hasRuleId()) {
          setRuleId(other.getRuleId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setRuleId(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 ruleId = 1;
      public boolean hasRuleId() {
        return result.hasRuleId();
      }
      public int getRuleId() {
        return result.getRuleId();
      }
      public Builder setRuleId(int value) {
        result.hasRuleId = true;
        result.ruleId_ = value;
        return this;
      }
      public Builder clearRuleId() {
        result.hasRuleId = false;
        result.ruleId_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.tiger_server.protocol.TigerRequest)
    }
    
    static {
      defaultInstance = new TigerRequest(true);
      com.randioo.tiger_server.protocol.Tiger.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.tiger_server.protocol.TigerRequest)
  }
  
  public static final class TigerResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use TigerResponse.newBuilder() to construct.
    private TigerResponse() {
      initFields();
    }
    private TigerResponse(boolean noInit) {}
    
    private static final TigerResponse defaultInstance;
    public static TigerResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public TigerResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.tiger_server.protocol.Tiger.internal_static_com_randioo_tiger_server_protocol_TigerResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.tiger_server.protocol.Tiger.internal_static_com_randioo_tiger_server_protocol_TigerResponse_fieldAccessorTable;
    }
    
    // optional int32 errorCode = 1 [default = 1];
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private boolean hasErrorCode;
    private int errorCode_ = 1;
    public boolean hasErrorCode() { return hasErrorCode; }
    public int getErrorCode() { return errorCode_; }
    
    // optional int32 result = 2;
    public static final int RESULT_FIELD_NUMBER = 2;
    private boolean hasResult;
    private int result_ = 0;
    public boolean hasResult() { return hasResult; }
    public int getResult() { return result_; }
    
    // optional .com.randioo.tiger_server.protocol.RandomData randomData = 3;
    public static final int RANDOMDATA_FIELD_NUMBER = 3;
    private boolean hasRandomData;
    private com.randioo.tiger_server.protocol.Entity.RandomData randomData_;
    public boolean hasRandomData() { return hasRandomData; }
    public com.randioo.tiger_server.protocol.Entity.RandomData getRandomData() { return randomData_; }
    
    // optional int32 free = 4;
    public static final int FREE_FIELD_NUMBER = 4;
    private boolean hasFree;
    private int free_ = 0;
    public boolean hasFree() { return hasFree; }
    public int getFree() { return free_; }
    
    private void initFields() {
      randomData_ = com.randioo.tiger_server.protocol.Entity.RandomData.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasErrorCode()) {
        output.writeInt32(1, getErrorCode());
      }
      if (hasResult()) {
        output.writeInt32(2, getResult());
      }
      if (hasRandomData()) {
        output.writeMessage(3, getRandomData());
      }
      if (hasFree()) {
        output.writeInt32(4, getFree());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasErrorCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getErrorCode());
      }
      if (hasResult()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getResult());
      }
      if (hasRandomData()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getRandomData());
      }
      if (hasFree()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, getFree());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.tiger_server.protocol.Tiger.TigerResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Tiger.TigerResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Tiger.TigerResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Tiger.TigerResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Tiger.TigerResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Tiger.TigerResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Tiger.TigerResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Tiger.TigerResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.tiger_server.protocol.Tiger.TigerResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.tiger_server.protocol.Tiger.TigerResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.tiger_server.protocol.Tiger.TigerResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.tiger_server.protocol.Tiger.TigerResponse result;
      
      // Construct using com.randioo.tiger_server.protocol.Tiger.TigerResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.tiger_server.protocol.Tiger.TigerResponse();
        return builder;
      }
      
      protected com.randioo.tiger_server.protocol.Tiger.TigerResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.tiger_server.protocol.Tiger.TigerResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.tiger_server.protocol.Tiger.TigerResponse.getDescriptor();
      }
      
      public com.randioo.tiger_server.protocol.Tiger.TigerResponse getDefaultInstanceForType() {
        return com.randioo.tiger_server.protocol.Tiger.TigerResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.tiger_server.protocol.Tiger.TigerResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.tiger_server.protocol.Tiger.TigerResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.tiger_server.protocol.Tiger.TigerResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.tiger_server.protocol.Tiger.TigerResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.tiger_server.protocol.Tiger.TigerResponse) {
          return mergeFrom((com.randioo.tiger_server.protocol.Tiger.TigerResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.tiger_server.protocol.Tiger.TigerResponse other) {
        if (other == com.randioo.tiger_server.protocol.Tiger.TigerResponse.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        if (other.hasRandomData()) {
          mergeRandomData(other.getRandomData());
        }
        if (other.hasFree()) {
          setFree(other.getFree());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setErrorCode(input.readInt32());
              break;
            }
            case 16: {
              setResult(input.readInt32());
              break;
            }
            case 26: {
              com.randioo.tiger_server.protocol.Entity.RandomData.Builder subBuilder = com.randioo.tiger_server.protocol.Entity.RandomData.newBuilder();
              if (hasRandomData()) {
                subBuilder.mergeFrom(getRandomData());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setRandomData(subBuilder.buildPartial());
              break;
            }
            case 32: {
              setFree(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 errorCode = 1 [default = 1];
      public boolean hasErrorCode() {
        return result.hasErrorCode();
      }
      public int getErrorCode() {
        return result.getErrorCode();
      }
      public Builder setErrorCode(int value) {
        result.hasErrorCode = true;
        result.errorCode_ = value;
        return this;
      }
      public Builder clearErrorCode() {
        result.hasErrorCode = false;
        result.errorCode_ = 1;
        return this;
      }
      
      // optional int32 result = 2;
      public boolean hasResult() {
        return result.hasResult();
      }
      public int getResult() {
        return result.getResult();
      }
      public Builder setResult(int value) {
        result.hasResult = true;
        result.result_ = value;
        return this;
      }
      public Builder clearResult() {
        result.hasResult = false;
        result.result_ = 0;
        return this;
      }
      
      // optional .com.randioo.tiger_server.protocol.RandomData randomData = 3;
      public boolean hasRandomData() {
        return result.hasRandomData();
      }
      public com.randioo.tiger_server.protocol.Entity.RandomData getRandomData() {
        return result.getRandomData();
      }
      public Builder setRandomData(com.randioo.tiger_server.protocol.Entity.RandomData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasRandomData = true;
        result.randomData_ = value;
        return this;
      }
      public Builder setRandomData(com.randioo.tiger_server.protocol.Entity.RandomData.Builder builderForValue) {
        result.hasRandomData = true;
        result.randomData_ = builderForValue.build();
        return this;
      }
      public Builder mergeRandomData(com.randioo.tiger_server.protocol.Entity.RandomData value) {
        if (result.hasRandomData() &&
            result.randomData_ != com.randioo.tiger_server.protocol.Entity.RandomData.getDefaultInstance()) {
          result.randomData_ =
            com.randioo.tiger_server.protocol.Entity.RandomData.newBuilder(result.randomData_).mergeFrom(value).buildPartial();
        } else {
          result.randomData_ = value;
        }
        result.hasRandomData = true;
        return this;
      }
      public Builder clearRandomData() {
        result.hasRandomData = false;
        result.randomData_ = com.randioo.tiger_server.protocol.Entity.RandomData.getDefaultInstance();
        return this;
      }
      
      // optional int32 free = 4;
      public boolean hasFree() {
        return result.hasFree();
      }
      public int getFree() {
        return result.getFree();
      }
      public Builder setFree(int value) {
        result.hasFree = true;
        result.free_ = value;
        return this;
      }
      public Builder clearFree() {
        result.hasFree = false;
        result.free_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.tiger_server.protocol.TigerResponse)
    }
    
    static {
      defaultInstance = new TigerResponse(true);
      com.randioo.tiger_server.protocol.Tiger.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.tiger_server.protocol.TigerResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_tiger_server_protocol_TigerRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_tiger_server_protocol_TigerRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_tiger_server_protocol_TigerResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_tiger_server_protocol_TigerResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Tiger.proto\022!com.randioo.tiger_server." +
      "protocol\032\014Entity.proto\"\036\n\014TigerRequest\022\016" +
      "\n\006ruleId\030\001 \001(\005\"\206\001\n\rTigerResponse\022\024\n\terro" +
      "rCode\030\001 \001(\005:\0011\022\016\n\006result\030\002 \001(\005\022A\n\nrandom" +
      "Data\030\003 \001(\0132-.com.randioo.tiger_server.pr" +
      "otocol.RandomData\022\014\n\004free\030\004 \001(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_tiger_server_protocol_TigerRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_tiger_server_protocol_TigerRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_tiger_server_protocol_TigerRequest_descriptor,
              new java.lang.String[] { "RuleId", },
              com.randioo.tiger_server.protocol.Tiger.TigerRequest.class,
              com.randioo.tiger_server.protocol.Tiger.TigerRequest.Builder.class);
          internal_static_com_randioo_tiger_server_protocol_TigerResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_randioo_tiger_server_protocol_TigerResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_tiger_server_protocol_TigerResponse_descriptor,
              new java.lang.String[] { "ErrorCode", "Result", "RandomData", "Free", },
              com.randioo.tiger_server.protocol.Tiger.TigerResponse.class,
              com.randioo.tiger_server.protocol.Tiger.TigerResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.tiger_server.protocol.Entity.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
